import { jsPDF } from 'jspdf'

/**
 * Generates a professional PDF worksheet from a unit's questions.
 */
export const exportUnitToPDF = (subject, unit) => {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let yPos = 20

  // Header Branding
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(24)
  doc.setTextColor(37, 99, 235) // Blue-600
  doc.text('ExamCraft AI', 20, yPos)
  
  yPos += 10
  doc.setFontSize(10)
  doc.setTextColor(150)
  doc.text('PROFESSIONAL EVALUATION SERIES', 20, yPos)

  // Subject & Unit Info
  yPos += 20
  doc.setFontSize(18)
  doc.setTextColor(30)
  doc.text(subject.name.toUpperCase(), 20, yPos)
  
  yPos += 10
  doc.setFontSize(14)
  doc.setFont('helvetica', 'normal')
  doc.text(`Unit: ${unit.title}`, 20, yPos)

  yPos += 15
  doc.setDrawColor(230)
  doc.line(20, yPos, pageWidth - 20, yPos)
  
  // Instructions
  yPos += 15
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('INSTRUCTIONS:', 20, yPos)
  yPos += 7
  doc.setFont('helvetica', 'normal')
  doc.text('Please answer all questions clearly. Ensure your handwriting is legible.', 20, yPos)

  yPos += 15

  // Questions
  unit.questions.forEach((q, index) => {
    // Check if we need a new page
    if (yPos > 270) {
      doc.addPage()
      yPos = 20
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text(`QUESTION ${index + 1}`, 20, yPos)
    
    yPos += 7
    doc.setFont('helvetica', 'normal')
    const splitQuestion = doc.splitTextToSize(q.question, pageWidth - 40)
    doc.text(splitQuestion, 20, yPos)
    
    yPos += (splitQuestion.length * 7) + 5

    // Render options for MCQ
    if (q.type === 'mcq' && q.options) {
      q.options.forEach((opt, optIdx) => {
        const char = String.fromCharCode(65 + optIdx) // A, B, C...
        doc.text(`(${char}) ${opt}`, 25, yPos)
        yPos += 7
      })
    } else {
      // Add lines for other types
      doc.setDrawColor(240)
      for (let i = 0; i < 3; i++) {
        doc.line(20, yPos, pageWidth - 20, yPos)
        yPos += 10
      }
    }

    yPos += 10
  })

  // Footer
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(180)
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: 'center' })
    doc.text('Generated by ExamCraft AI Synthesizer', pageWidth - 20, 285, { align: 'right' })
  }

  doc.save(`${subject.name}_${unit.title}_Worksheet.pdf`)
}
